# config/config.yaml
experiment_name: "nih_chest_xray_training"
seed: 42

data:
  # Для быстрого обучения используйте subset файлы
  train_csv: "data/subset_train.csv"  # или "data/train.csv" для полного датасета
  val_csv: "data/subset_val.csv"
  test_csv: "data/subset_test.csv"
  img_dir: "data/nih_chest_xrays"  # Не используется если в CSV полные пути
  batch_size: 16
  num_workers: 2  # Увеличьте для быстрой загрузки

model:
  backbone: "resnet50"
  num_classes: 14
  pretrained: true  # Теперь можно использовать true
  use_attention: false
  dropout_rate: 0.5

training:
  num_epochs: 20  # Увеличьте для лучших результатов
  learning_rate: 0.0001
  weight_decay: 0.00001
  gradient_accumulation_steps: 2
  max_grad_norm: 1.0
  early_stopping_patience: 5